use crate::ir::StringId;
use crate::schema::{
    BinaryNumberCheckPolicy, TextNumberJustification, TextNumberRep, TextNumberRounding,
    TextNumberRoundingMode, TextPadKind, TextStringJustification, TextTrimKind, TextZonedSignStyle,
};
use alloc::string::String;

#[derive(Debug, Clone, PartialEq)]
pub struct TextProps {
    pub text_trim_kind: TextTrimKind,
    pub text_pad_kind: TextPadKind,
    pub truncate_specified_length_string: bool,
    pub text_number_pad_character: Option<StringId>,
    pub text_number_pad_character_property_form: bool,
    pub text_string_pad_character: Option<StringId>,
    pub text_string_pad_character_property_form: bool,
    pub text_calendar_pad_character: Option<StringId>,
    pub text_calendar_justification: Option<TextStringJustification>,
    pub text_number_pattern: Option<StringId>,
    pub text_number_check_policy: BinaryNumberCheckPolicy,
    pub text_number_rep: TextNumberRep,
    pub text_number_rounding: TextNumberRounding,
    pub text_number_rounding_increment: StringId,
    pub text_number_rounding_mode: TextNumberRoundingMode,
    pub text_number_rounding_increment_defined: bool,
    pub text_zoned_sign_style: Option<TextZonedSignStyle>,
    pub text_standard_decimal_separator: StringId,
    pub text_standard_decimal_separator_defined: bool,
    pub text_standard_decimal_separator_sibling: Option<StringId>,
    pub text_standard_grouping_separator: Option<StringId>,
    pub text_standard_grouping_separator_defined: bool,
    pub text_standard_grouping_separator_sibling: Option<StringId>,
    pub text_standard_exponent_rep: StringId,
    pub text_standard_exponent_rep_sibling: Option<StringId>,
    pub text_standard_infinity_rep: StringId,
    pub text_standard_nan_rep: StringId,
    pub text_standard_zero_rep: StringId,
    pub text_standard_zero_rep_defined: bool,
    pub text_standard_exponent_rep_defined: bool,
    pub resolved_text_standard_decimal_separator: Option<String>,
    pub resolved_text_standard_grouping_separator: Option<String>,
    pub resolved_text_standard_exponent_rep: Option<String>,
    pub custom_text_number_pattern: bool,
    pub text_boolean_true_rep: Option<StringId>,
    pub text_boolean_false_rep: Option<StringId>,
    pub text_boolean_true_rep_defined: bool,
    pub text_boolean_false_rep_defined: bool,
    pub text_boolean_pad_character: Option<StringId>,
    pub text_string_justification: TextStringJustification,
    pub text_number_justification: TextNumberJustification,
    pub text_standard_base: u32,
}

impl Default for TextProps {
    fn default() -> Self {
        Self {
            text_trim_kind: TextTrimKind::None,
            text_pad_kind: TextPadKind::None,
            truncate_specified_length_string: false,
            text_number_pad_character: None,
            text_number_pad_character_property_form: false,
            text_string_pad_character: None,
            text_string_pad_character_property_form: false,
            text_calendar_pad_character: None,
            text_calendar_justification: None,
            text_number_pattern: None,
            text_number_check_policy: BinaryNumberCheckPolicy::Lax,
            text_number_rep: TextNumberRep::Standard,
            text_number_rounding: TextNumberRounding::Pattern,
            text_number_rounding_increment: StringId(0),
            text_number_rounding_mode: TextNumberRoundingMode::HalfEven,
            text_number_rounding_increment_defined: false,
            text_zoned_sign_style: None,
            text_standard_decimal_separator: StringId(0),
            text_standard_decimal_separator_defined: false,
            text_standard_decimal_separator_sibling: None,
            text_standard_grouping_separator: None,
            text_standard_grouping_separator_defined: false,
            text_standard_grouping_separator_sibling: None,
            text_standard_exponent_rep: StringId(0),
            text_standard_exponent_rep_sibling: None,
            text_standard_infinity_rep: StringId(0),
            text_standard_nan_rep: StringId(0),
            text_standard_zero_rep: StringId(0),
            text_standard_zero_rep_defined: false,
            text_standard_exponent_rep_defined: false,
            resolved_text_standard_decimal_separator: None,
            resolved_text_standard_grouping_separator: None,
            resolved_text_standard_exponent_rep: None,
            custom_text_number_pattern: false,
            text_boolean_true_rep: None,
            text_boolean_false_rep: None,
            text_boolean_true_rep_defined: false,
            text_boolean_false_rep_defined: false,
            text_boolean_pad_character: None,
            text_string_justification: TextStringJustification::Left,
            text_number_justification: TextNumberJustification::Right,
            text_standard_base: 10,
        }
    }
}
