<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:dfdl="http://www.ogf.org/dfdl/dfdl-1.0/">
  <xs:include schemaLocation="nmea_types.xsd"/>

  <xs:element name="GPVTG" dfdl:terminator="%CR;%LF;">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="body" dfdl:initiator="$GPVTG," dfdl:terminator="*" dfdl:lengthKind="implicit">
          <xs:complexType>
            <xs:sequence dfdl:separator="," dfdl:separatorPosition="infix">
              <xs:element name="trackTrue" type="NmeaAngle"/>
              <xs:element name="trackTrueUnit" type="NmeaTrackUnitTrue"/>
              <xs:element name="trackMagnetic" type="NmeaAngle" minOccurs="0"/>
              <xs:element name="trackMagneticUnit" type="NmeaTrackUnitMagnetic" minOccurs="0"/>
              <xs:element name="speedKnots" type="NmeaAngle"/>
              <xs:element name="speedKnotsUnit" type="NmeaSpeedUnitKnots"/>
              <xs:element name="speedKmh" type="NmeaAngle"/>
              <xs:element name="speedKmhUnit" type="NmeaSpeedUnitKmh"/>
              <xs:element name="mode" type="NmeaMode" minOccurs="0"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="checksum" type="NmeaChecksum"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>
