<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:dfdl="http://www.ogf.org/dfdl/dfdl-1.0/">
  <xs:include schemaLocation="nmea_types.xsd"/>

  <xs:element name="AIVDM" dfdl:terminator="%CR;%LF;">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="body" dfdl:initiator="!AIVDM," dfdl:terminator="*" dfdl:lengthKind="implicit">
          <xs:complexType>
            <xs:sequence dfdl:separator="," dfdl:separatorPosition="infix">
              <xs:element name="totalSentences" type="NmeaAisSentenceCount"/>
              <xs:element name="sentenceNumber" type="NmeaAisSentenceCount"/>
              <xs:element name="sequentialId" type="xs:string" minOccurs="0"/>
              <xs:element name="channel" type="NmeaAisChannel"/>
              <xs:element name="payload" type="xs:string"/>
              <xs:element name="fillBits" type="NmeaFillBits"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="checksum" type="NmeaChecksum"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>
