<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:dfdl="http://www.ogf.org/dfdl/dfdl-1.0/">
  <xs:include schemaLocation="sbs_types.xsd"/>

  <xs:element name="SbsMsg" dfdl:terminator="%CR;%LF;">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="body" dfdl:initiator="MSG," dfdl:lengthKind="implicit">
          <xs:complexType>
            <xs:sequence dfdl:separator="," dfdl:separatorPosition="infix">
              <xs:element name="transmissionType" type="SbsTransmissionType"/>
              <xs:element name="sessionId" type="xs:unsignedInt"/>
              <xs:element name="aircraftId" type="xs:unsignedInt"/>
              <xs:element name="hexIdent" type="SbsHexIdent"/>
              <xs:element name="flightId" type="xs:unsignedInt"/>
              <xs:element name="dateGenerated" type="SbsDate"/>
              <xs:element name="timeGenerated" type="SbsTime"/>
              <xs:element name="dateLogged" type="SbsDate"/>
              <xs:element name="timeLogged" type="SbsTime"/>
              <xs:element name="callsign" type="SbsCallsign"/>
              <xs:element name="altitude" type="SbsOptionalUnsignedInt"/>
              <xs:element name="groundSpeed" type="SbsOptionalUnsignedInt"/>
              <xs:element name="track" type="SbsOptionalSignedDecimal"/>
              <xs:element name="latitude" type="SbsOptionalLatitude"/>
              <xs:element name="longitude" type="SbsOptionalLongitude"/>
              <xs:element name="verticalRate" type="SbsOptionalSignedDecimal"/>
              <xs:element name="squawk" type="SbsOptionalSquawk"/>
              <xs:element name="alert" type="SbsOptionalFlag"/>
              <xs:element name="emergency" type="SbsOptionalFlag"/>
              <xs:element name="spi" type="SbsOptionalFlag"/>
              <xs:element name="isOnGround" type="SbsOptionalFlag"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>
