<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:dfdl="http://www.ogf.org/dfdl/">
  <xs:element name="Message" type="MessageType">
    <xs:annotation>
      <xs:appinfo source="http://www.ogf.org/dfdl/">
        <dfdl:element representation="text" encoding="UTF-8"/>
      </xs:appinfo>
    </xs:annotation>
  </xs:element>

  <xs:complexType name="MessageType">
    <xs:sequence>
      <xs:element name="tag" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" lengthKind="fixed" length="3"/>
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="value" type="xs:int">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" lengthKind="delimited" terminator=";"/>
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:schema>
